// import Head from "next/head";
// import styles from "../../../styles/PJ/register.module.css";
// import {
//   Button,
//   FormControlLabel,
//   FormLabel,
//   Radio,
//   RadioGroup,
// } from "@mui/material";
// import { useState } from "react";
// import { Success } from "@/components/admin/Success";
// import { useRouter } from "next/router";

// export default function Register() {
//   const options = [
//     { value: "", text: "--Choose an option--" },
//     { value: "firstyear", text: "100" },
//     { value: "secondyear", text: "200" },
//     {value: 'thirdyear', text: '300'},
//     { value: "fouthyear", text: "400" },
//     // { value: "phas", text: "PHAS" },
//     // { value: "graduate", text: "Graduate schools" },
//   ];
//   const [selected, setSelected] = useState(options[0].value);

//   const router = useRouter();

//   const [register_info, setRegister_info] = useState({
//     firstname: "",
//     surname: "",
//     othername: "",
//     student_id: "",
//     email: "",
//     password: "",
//     gender: "",
//     department: "",
//   });
//   const handleChange = (event) => {
//     setSelected(event.target.value);
//     setRegister_info({ ...register_info, department: event.target.value });
//   };
//   const [Error_msg, setError_msg] = useState({ Errmsg: "", isValid: true });
//   const [Success_msg, setSuccess_msg] = useState({
//     success_msg: "",
//     register_success: false,
//   });

//   const handleRegister = async () => {
//     const res = await fetch("/api/Register", {
//       method: "POST",
//       headers: { "Content-Type": "application/json" },
//       body: JSON.stringify({
//         firstname: register_info.firstname,
//         surname: register_info.surname,
//         othername: register_info.othername,
//         student_id: register_info.student_id,
//         password: register_info.password,
//         email: register_info.email,
//         gender: register_info.gender,
//         department: register_info.department,
//       }),

//     });
//     const response = await res.json();
//     if (res.ok && response) {
//       return(
//         setSuccess_msg({
//           success_msg: response.message,
//           register_success: true,
//         }),
//         setTimeout(() => {
//           router.push("/projectJugler/u/login");
//         }, 1000)
//       )
//     } else {
//       setError_msg({ Errmsg: "The provided student ID has been rgistered", isValid: true });

//     }
//   };

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>project jugler</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/srcLogo.jpg" />
//       </Head>
//       <div className={styles.left}>
//         <div className={styles.items}>
//           <div className={styles.item}>
//             <h3>Register as a student of CUG</h3>
//           <p>{Error_msg.isValid ? Error_msg.Errmsg : ""}</p>
//           {Success_msg.register_success && <Success message={"Added successfully"}/>}
//             <br />
//             <hr />
//             <br />
//             <div className={styles.name}>
//               <input
//                 className={styles.input}
//                 type="text"
//                 placeholder="SurName"
//                 onInput={(e) =>
//                   setRegister_info({
//                     ...register_info,
//                     surname: e.target.value,
//                   })
//                 }
//               />
//               <input
//                 className={styles.input}
//                 type="text"
//                 placeholder="Firstname"
//                 onInput={(e) =>
//                   setRegister_info({
//                     ...register_info,
//                     firstname: e.target.value,
//                   })
//                 }
//               />
//             </div>
//             <div className={styles.name}>
//               <input
//                 className={styles.input}
//                 type="text"
//                 placeholder="OtherName (optional)"
//                 onInput={(e) =>
//                   setRegister_info({
//                     ...register_info,
//                     othername: e.target.value,
//                   })
//                 }
//               />
//               <input
//                 className={styles.input}
//                 type="text"
//                 placeholder="Email"
//                 onInput={(e) =>
//                   setRegister_info({
//                     ...register_info,
//                     email: e.target.value,
//                   })
//                 }
//               />
//             </div>
//             <div className={styles.name}>
//               <input
//                 className={styles.input}
//                 type="text"
//                 placeholder="Student ID"
//                 onInput={(e) =>
//                   setRegister_info({
//                     ...register_info,
//                     student_id: e.target.value,
//                   })
//                 }
//               />
//             </div>
//             <h3 className={styles.label}>Level</h3>
//             <select
//               value={selected}
//               onChange={handleChange}
//               className={styles.dropdown}
//               placeholder="Level"

//               // onInput={(e) =>
//               //   setRegister_info({
//               //     ...register_info,
//               //     department: e.target.value,
//               //   })
//               // }
//             >
//               {options.map((option) => (
//                 <option key={option.value} value={option.value}>
//                   {option.text}
//                 </option>
//               ))}
//             </select>
//             <div className={styles.gender}>
//               {/* <FormLabel className={styles.gender}>Gender</FormLabel> */}
//               <RadioGroup
//                 row
//                 // defaultValue="female"
//                 // onInput={(e) =>
//                 //   setRegister_info({ ...register_info, gender: e.target.value })
//                 // }
//               >
//                 <FormControlLabel
//                   value="female"
//                   className={styles.gen}
//                   control={<Radio />}
//                   label="Female"
//                   onInput={(e) =>
//                     setRegister_info({ ...register_info, gender: e.target.value })
//                   }
//                 />
//                 <FormControlLabel
//                   value="male"
//                   className={styles.gen}
//                   control={<Radio />}
//                   label="Male"
//                   onInput={(e) =>
//                     setRegister_info({ ...register_info, gender: e.target.value })
//                   }
//                 />
//                 <FormControlLabel
//                   value="other"
//                   className={styles.gen}
//                   control={<Radio />}
//                   label="Other"
//                   onInput={(e) =>
//                     setRegister_info({ ...register_info, gender: e.target.value })
//                   }
//                 />
//               </RadioGroup>
//             </div>
//             <div className={styles.name}>
//               <input
//                 className={styles.input}
//                 type="password"
//                 placeholder="Password"
//                 onInput={(e) =>
//                   setRegister_info({
//                     ...register_info,
//                     password: e.target.value,
//                   })
//                 }
//               />
//               <input
//                 className={styles.input}
//                 type="password"
//                 placeholder="Confirm Password"
//                 onInput={(e) =>
//                   setRegister_info({
//                     ...register_info,
//                     password: e.target.value,
//                   })
//                 }
//               />
//             </div>
//           </div>
//           <Button onClick={() => handleRegister()} className={styles.btn}>
//             Register
//           </Button>
//         </div>
//       </div>
//       <div className={styles.right}></div>
//     </div>
//   );
// }

import Navbar from "@/components/projectJugler/Navbar";


export default function About() {
  return (
    <div>
      <Navbar />
      
      {/* <h3>Project Jugler</h3> */}
    </div>
  )
}
