import Head from "next/head";
import React from "react";
import Navbar from "@/components/projectJugler/Navbar";
import Featured from "@/components/projectJugler/Featured";
import styles from "../../../styles/PJ/Navbar.module.css";



export default function index() {
  return (
    <div className={styles.body}>
      <Head>
        <title>PJ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/srcLogo.jpg" />
      </Head>
      <Navbar />
      <div>
        <Featured />
      </div>
    </div>
  );
}
