import { useState } from "react";
import Navbar from "@/components/projectJugler/Navbar";
import Head from "next/head";
import Pagination from "../../../components/Pagination";
import Footer from "@/components/projectJugler/Footer";
import axios from "axios";
import { getserver } from "@/config";
import Link from "next/link";
import { paginate } from "@/utils/paginate";
import styles from "../../../styles/PJ/Project.module.css"


const ParentComponent = ({ projectsData }) => {
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 2;
  const [searchQuery, setSearchQuery] = useState("");

  const handleSearch = (e) => {
    setSearchQuery(e.target.value);
  };

  const onPageChange = (page) => {
    setCurrentPage(page);
  };

  const filteredProjects = projectsData.filter((p) =>
    p.title.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const paginatedProjects = paginate(filteredProjects, currentPage, pageSize);

  return (
    <>
      <Head>
        <title>PJ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/srcLogo.jpg" />
      </Head>
      <Navbar />
      <div className={styles.generalContent}>
        <p className={styles.pagenum}>Page {currentPage}</p>

        <div className={styles.generalitems}>
          <input
            type="text"
            value={searchQuery}
            onChange={handleSearch}
            placeholder="Search projects..."
            className={styles.search}
          />

          {paginatedProjects.map((projectInfo) => (
            <div key={projectInfo.id} className={styles.project}>
              <Link href={`/projectJugler/u/Projects/${projectInfo.id}`}>
                <div className={styles.item}>
                  <h3 className={styles.projecttitle}>{projectInfo.title}</h3>
                  <p className={styles.projectabstract}>
                    {projectInfo.abstract.slice(0, 750)}....
                  </p>
                  <h5 className={styles.projectyear}>{projectInfo.year}</h5>
                </div>
              </Link>
            </div>
          ))}
        </div>
      </div>
      <div>
        <Pagination
          items={filteredProjects.length}
          currentPage={currentPage}
          pageSize={pageSize}
          onPageChange={onPageChange}
        />
      </div>
      <Footer />
    </>
  );
};

export default ParentComponent;

export const getServerSideProps = async () => {
  const res = await axios.get(`${getserver}/api/Project`);
  return {
    props: {
      projectsData: res.data,
    },
  };
};
